[[redirects]]
  from = "/graphql"
  to = "http://dev.execreator.com/graphql"
  status = 200
  force = true

 [[redirects]]
  from = "/subscription"
  to = "https://push-notification-demo-server.herokuapp.com/subscription"
  status = 200
  force = true